version: '3.8'
services:
  db:
    image: postgres:16.9
    container_name: fs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: fsdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: fs-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD:
    command: server /data --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: fs-redis
    ports:
      - "6379:6379"

  file-storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fs-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - minio

volumes:
  postgres_data:
  minio_data: