version: '3.8'
services:
  db:
    image: postgres:16.9
    container_name: fs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/docker/volumes/postgres_data/

  pgadmin:
    container_name: fs-pgadmin
    image: dpage/pgadmin4:9.6
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/docker/volumes/pgadmin

  minio:
    image: minio/minio:latest
    container_name: fs-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server ~/data --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: fs-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  pgadmin_data:
  minio_data: